# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        /blog/post/:year-:month-:day/:title
#relative_permalinks: true

# Setup
title:            matthid
tagline:          'Just another blog'
description:      'Some thoughts about about some of the stuff I do. You can find me on twitter <a href="https://twitter.com/matthi__d" target="_blank">@matthi__d</a> and on github <a href="https://github.com/matthid/" target="_blank">@matthid</a>.'
url:              https://matthid.de
baseurl:          /

author:
  name:           'Matthias Dittrich'
  url:            https://twitter.com/matthi__d

plugins: [jekyll-paginate]
paginate:         5

# Custom vars
#version:          2.1.0

github:
  repo:           https://github.com/matthid
